version: "0.1"

processes:
  postgres:
    command: 'postgres -p5432 -k ${XDG_STATE_HOME} -c logging_collector=off -c log_destination=stderr -c log_min_messages=INFO -c log_statement=all'
    is_daemon: true
    readiness_probe:
      exec:
      command: "pg_isready -p5432"
      interval: 5s
    environment:
      - PGDATA=${PGDATA}
      - PGHOST=${PGHOST}
    availability:
      restart: "always"
    shutdown:
      command: "pg_ctl stop -D ${PGDATA} -m fast"
      signal: 2  # INT
      timeout: 30s

  memcached:
    command: "memcached -u nobody -m 64 -p 11211"
    disabled: true
    shutdown:
      signal: 15  # TERM
      timeout: 10s
    readiness_probe:
      exec:
        command: "ss -tanl | grep 11211"
      interval: 5s
      timeout: 2s

  rabbitmq:
    command: "rabbitmq-server"
    disabled: true
    shutdown:
      command: "rabbitmqctl stop"
      timeout: 20s
    readiness_probe:
      exec:
        command: "rabbitmqctl -n ${RABBITMQ_NODENAME} status"
      interval: 5s
      initial_delay: 10s
      timeout: 3s


  socratic-api:
    command: "socratic-cli web serve socratic"
    disabled: true
    depends_on:
      postgres:
        condition: process_healthy
    readiness_probe:
      http_get:
        host: 127.0.0.1
        port: 8080
        path: /openapi.json
      interval: 5s
      timeout: 2s
    shutdown:
      signal: 15  # TERM
      timeout: 10s

  socratic-dev:
    command: "socratic-cli web develop socratic"
    disabled: false
    depends_on:
      postgres:
        condition: process_healthy
    readiness_probe:
      http_get:
        host: 127.0.0.1
        port: 8080
        path: /openapi.json
      interval: 5s
      timeout: 2s
    shutdown:
      signal: 15  # TERM
      timeout: 10s

  socratic-vite:
    command: "npm run dev --prefix socratic/web/socratic/frontend -- --port 5173"
    disabled: false
    working_dir: .
    readiness_probe:
      http_get:
        host: 127.0.0.1
        port: 5173
        path: /static
      interval: 5s
      timeout: 2s
    shutdown:
      signal: 15  # TERM
      timeout: 10s
