version: '0.1'

processes:
  postgres:
    command: 'postgres -p5432 -k ${XDG_DATA_HOME} -c logging_collector=off -c log_destination=stderr -c log_min_messages=INFO -c log_statement=all'
    is_daemon: false
    readiness_probe:
      exec:
        command: 'pg_isready -h ${XDG_DATA_HOME} -p5432'
      initial_delay_seconds: 2
      period_seconds: 30
    environment:
      - PGDATA=${PGDATA}
      - PGHOST=${PGHOST}
    availability:
      restart: 'always'
    shutdown:
      command: 'pg_ctl stop -D ${PGDATA} -m fast'
      signal: 2 # INT
      timeout_seconds: 30

  memcached:
    command: 'memcached -u nobody -m 64 -p 11211'
    disabled: true
    shutdown:
      signal: 15 # TERM
      timeout_Seconds: 10s
    readiness_probe:
      exec:
        command: 'ss -tanl | grep 11211'
      period_seconds: 5

  redis:
    command: |
      mkdir -p ${XDG_DATA_HOME}/redis
      redis-server --unixsocket ${REDIS_SOCKET_PATH} --unixsocketperm 700 --port 0 --daemonize no --dir ${XDG_DATA_HOME}/redis
    is_daemon: false
    readiness_probe:
      exec:
        command: 'redis-cli -s ${REDIS_SOCKET_PATH} ping'
      initial_delay_seconds: 1
      period_seconds: 10
    shutdown:
      signal: 15 # TERM
      timeout_seconds: 10

  rabbitmq:
    command: 'rabbitmq-server'
    disabled: true
    shutdown:
      command: 'rabbitmqctl stop'
      timeout: 20s
    readiness_probe:
      exec:
        command: 'rabbitmqctl -n ${RABBITMQ_NODENAME} status'
      initial_delay_seconds: 10
      period_seconds: 5

  socratic-api:
    command: 'socratic-cli web serve socratic'
    disabled: true
    depends_on:
      postgres:
        condition: process_healthy
      redis:
        condition: process_healthy
    readiness_probe:
      http_get:
        host: 127.0.0.1
        port: 8089
        path: /openapi.json
      period_seconds: 30
      initial_delay_seconds: 6
    shutdown:
      signal: 15 # TERM
      timeout_seconds: 10

  socratic-dev:
    command: 'socratic-cli web develop socratic'
    depends_on:
      postgres:
        condition: process_healthy
      redis:
        condition: process_healthy
    readiness_probe:
      http_get:
        host: 127.0.0.1
        port: 8089
        path: /openapi.json
      period_seconds: 30
      initial_delay_seconds: 6
    shutdown:
      signal: 15 # TERM
      timeout_seconds: 10

  socratic-agent:
    command: 'socratic-cli agent serve'
    disabled: true
    depends_on:
      postgres:
        condition: process_healthy
      redis:
        condition: process_healthy
    shutdown:
      signal: 15 # TERM
      timeout_seconds: 10

  socratic-vite:
    command: 'npm run dev --prefix socratic/web/socratic/frontend -- --host 127.0.0.1 --port 9099'
    working_dir: .
    environment:
      - 'VITE_API_URL=http://127.0.0.1:8089'
    depends_on:
      socratic-dev:
        condition: process_healthy
    readiness_probe:
      http_get:
        host: 127.0.0.1
        port: 9099
        path: /static
      period_seconds: 30
      initial_delay_seconds: 2
    shutdown:
      signal: 15 # TERM
      timeout_seconds: 10
