import typing as t

class VaultSecret(object):
    def __init__(self, _bytes: bytes | None = None) -> None: ...
    @property
    def bytes(self) -> bytes: ...
    def load(self) -> bytes: ...

VaultID = str

class VaultLib(object):
    def __init__(self, secrets: t.Sequence[tuple[VaultID | None, VaultSecret]]) -> None: ...
    def decrypt(self, vaulttext: str, filename: str | None = None, obj: t.Any = None) -> bytes: ...
