from pathlib import Path

def xdg_cache_home() -> Path: ...
def xdg_config_dirs() -> list[Path]: ...
def xdg_config_home() -> Path: ...
def xdg_data_dirs() -> list[Path]: ...
def xdg_data_home() -> Path: ...
def xdg_runtime_dir() -> Path | None: ...
def xdg_state_home() -> Path: ...
