// This file is auto-generated by @hey-api/openapi-ts

export type AssessmentFlag =
  | 'high_fluency_low_substance'
  | 'repeated_evasion'
  | 'vocabulary_mirroring'
  | 'inconsistent_reasoning'
  | 'possible_gaming'
  | 'low_confidence';

/**
 * Current assessment status.
 */
export type AssessmentStatusResponse = {
  attempt_id: string;
  phase: string;
  message_count: number;
  prompts_completed: number;
  total_prompts: number;
  consent_confirmed: boolean;
};

/**
 * Request to create a new assignment.
 */
export type AssignmentCreateRequest = {
  objective_id: string;
  assigned_to: string;
  available_from?: string | null;
  available_until?: string | null;
  max_attempts?: number;
  retake_policy?: RetakePolicy;
  retake_delay_hours?: number | null;
};

/**
 * List of assignments response.
 */
export type AssignmentListResponse = {
  assignments: Array<AssignmentResponse>;
  total: number;
};

/**
 * Assignment details response.
 */
export type AssignmentResponse = {
  assignment_id: string;
  organization_id: string;
  objective_id: string;
  assigned_by: string;
  assigned_to: string;
  available_from?: string | null;
  available_until?: string | null;
  max_attempts: number;
  retake_policy: RetakePolicy;
  retake_delay_hours?: number | null;
  create_time: string;
  update_time?: string | null;
};

/**
 * Request to update an assignment.
 */
export type AssignmentUpdateRequest = {
  available_from?: string | null;
  available_until?: string | null;
  max_attempts?: number | null;
  retake_policy?: RetakePolicy | null;
  retake_delay_hours?: number | null;
};

/**
 * Assignment with attempt history.
 */
export type AssignmentWithAttemptsResponse = {
  assignment_id: string;
  organization_id: string;
  objective_id: string;
  assigned_by: string;
  assigned_to: string;
  available_from?: string | null;
  available_until?: string | null;
  max_attempts: number;
  retake_policy: RetakePolicy;
  retake_delay_hours?: number | null;
  create_time: string;
  update_time?: string | null;
  attempts?: Array<SocraticWebSocraticViewAssignmentAttemptResponse>;
  attempts_remaining?: number;
};

/**
 * Feedback from an evaluated/reviewed attempt.
 */
export type AttemptFeedback = {
  strengths?: Array<string>;
  gaps?: Array<string>;
  reasoning_summary?: string | null;
};

/**
 * Attempt with assignment and objective context for history view.
 */
export type AttemptHistoryItem = {
  attempt_id: string;
  assignment_id: string;
  objective_id: string;
  objective_title: string;
  objective_description?: string | null;
  status: AttemptStatus;
  grade?: Grade | null;
  confidence_score?: string | null;
  started_at?: string | null;
  completed_at?: string | null;
  create_time: string;
  has_evaluation?: boolean;
  evaluation_id?: string | null;
  feedback?: AttemptFeedback | null;
};

export type AttemptStatus =
  | 'not_started'
  | 'in_progress'
  | 'completed'
  | 'evaluated'
  | 'reviewed';

export type BodyTranscribeAudio = {
  file: Blob | File;
  language?: string | null;
};

/**
 * Request to create assignments for multiple learners.
 */
export type BulkAssignmentCreateRequest = {
  objective_id: string;
  assigned_to: Array<string>;
  available_from?: string | null;
  available_until?: string | null;
  max_attempts?: number;
  retake_policy?: RetakePolicy;
  retake_delay_hours?: number | null;
};

/**
 * Response after completing an assessment.
 */
export type CompleteAssessmentOkResponse = {
  attempt_id: string;
  status: string;
  completed_at: string;
};

/**
 * Request to complete an assessment.
 */
export type CompleteAssessmentRequest = {
  feedback?: string | null;
};

export type DependencyType = 'hard' | 'soft';

/**
 * Evaluation result for the review.
 */
export type EvaluationResponse = {
  evaluation_id: string;
  evidence_mappings: Array<EvidenceMappingResponse>;
  flags: Array<AssessmentFlag>;
  strengths: Array<string>;
  gaps: Array<string>;
  reasoning_summary: string | null;
  create_time: string;
};

/**
 * Evidence mapping for a rubric criterion.
 */
export type EvidenceMappingResponse = {
  criterion_id: string;
  criterion_name?: string | null;
  segment_ids: Array<string>;
  evidence_summary: string | null;
  strength: string | null;
  failure_modes_detected: Array<string>;
};

export type ExtensionPolicy = 'allowed' | 'disallowed' | 'conditional';

/**
 * Request to add feedback.
 */
export type FeedbackRequest = {
  feedback_text: string;
  visible_to_learner?: boolean;
};

export type Grade = 'S' | 'A' | 'C' | 'F';

/**
 * Request to accept the AI-assigned grade.
 */
export type GradeAcceptRequest = {
  [key: string]: unknown;
};

/**
 * Request to override the grade.
 */
export type GradeOverrideRequest = {
  new_grade: Grade;
  reason: string;
};

export type HttpValidationError = {
  detail?: Array<ValidationError>;
};

/**
 * Request body for inviting a user to an organization.
 */
export type InviteRequest = {
  email: string;
  role: string;
};

/**
 * Response containing invite token.
 */
export type InviteResponse = {
  invite_token: string;
  email: string;
  organization_id: string;
  role: string;
  expires_at: string;
};

/**
 * Summary of a learner's assignment status.
 */
export type LearnerAssignmentSummary = {
  assignment_id: string;
  objective_id: string;
  objective_title: string;
  objective_description?: string | null;
  expected_duration_minutes?: number | null;
  status: AttemptStatus;
  grade?: Grade | null;
  attempts_used: number;
  attempts_remaining: number;
  available_from?: string | null;
  available_until?: string | null;
  is_available?: boolean;
  is_locked?: boolean;
};

/**
 * List of assignments for a learner.
 */
export type LearnerAssignmentsListResponse = {
  assignments: Array<LearnerAssignmentSummary>;
  total: number;
};

/**
 * List of attempts for a learner.
 */
export type LearnerAttemptsListResponse = {
  attempts: Array<AttemptHistoryItem>;
  total: number;
};

/**
 * Learner dashboard with all assignments.
 */
export type LearnerDashboardResponse = {
  assignments: Array<LearnerAssignmentSummary>;
  total_completed: number;
  total_in_progress: number;
  total_pending: number;
};

/**
 * List of learners response.
 */
export type LearnerListResponse = {
  learners: Array<LearnerResponse>;
  total: number;
};

/**
 * Learner information for educators.
 */
export type LearnerResponse = {
  user_id: string;
  email: string;
  name: string;
};

/**
 * Response for successful login.
 */
export type LoginOkResponse = {
  user: UserResponse;
  token: TokenResponse;
};

/**
 * Request body for login.
 */
export type LoginRequest = {
  email: string;
  password: string;
};

/**
 * Request to create a new objective.
 */
export type ObjectiveCreateRequest = {
  title: string;
  description: string;
  scope_boundaries?: string | null;
  time_expectation_minutes?: number | null;
  initial_prompts?: Array<string>;
  challenge_prompts?: Array<string>;
  extension_policy?: ExtensionPolicy;
  rubric_criteria?: Array<RubricCriterionRequest>;
};

/**
 * Request to add a dependency between objectives.
 */
export type ObjectiveDependencyRequest = {
  depends_on_objective_id: string;
  dependency_type?: DependencyType;
};

/**
 * Dependency between objectives.
 */
export type ObjectiveDependencyResponse = {
  objective_id: string;
  depends_on_objective_id: string;
  dependency_type: DependencyType;
};

/**
 * Request to add an objective to a strand.
 */
export type ObjectiveInStrandRequest = {
  objective_id: string;
  position: number;
};

/**
 * Objective position in strand.
 */
export type ObjectiveInStrandResponse = {
  strand_id: string;
  objective_id: string;
  position: number;
};

/**
 * List of objectives response.
 */
export type ObjectiveListResponse = {
  objectives: Array<ObjectiveResponse>;
  total: number;
};

/**
 * Objective details response.
 */
export type ObjectiveResponse = {
  objective_id: string;
  organization_id: string;
  created_by: string;
  title: string;
  description: string;
  scope_boundaries?: string | null;
  time_expectation_minutes?: number | null;
  initial_prompts?: Array<string>;
  challenge_prompts?: Array<string>;
  extension_policy: ExtensionPolicy;
  status: ObjectiveStatus;
  create_time: string;
  update_time?: string | null;
  rubric_criteria?: Array<RubricCriterionResponse>;
};

export type ObjectiveStatus = 'draft' | 'published' | 'archived';

/**
 * Request to update an objective.
 */
export type ObjectiveUpdateRequest = {
  title?: string | null;
  description?: string | null;
  scope_boundaries?: string | null;
  time_expectation_minutes?: number | null;
  initial_prompts?: Array<string> | null;
  challenge_prompts?: Array<string> | null;
  extension_policy?: ExtensionPolicy | null;
  status?: ObjectiveStatus | null;
};

/**
 * Request body for creating an organization.
 */
export type OrganizationCreateRequest = {
  name: string;
  slug: string;
  admin_email: string;
  admin_password: string;
  admin_name: string;
};

/**
 * Public response containing minimal organization information.
 *
 * Used for unauthenticated endpoints like login page validation.
 */
export type OrganizationPublicResponse = {
  organization_id: string;
  name: string;
  slug: string;
};

/**
 * Response containing organization information.
 */
export type OrganizationResponse = {
  organization_id: string;
  name: string;
  slug: string;
  create_time: string;
};

/**
 * An educator override record.
 */
export type OverrideResponse = {
  override_id: string;
  educator_id: string;
  educator_name?: string | null;
  original_grade: Grade | null;
  new_grade: Grade;
  reason: string;
  feedback: string | null;
  create_time: string;
};

/**
 * Proficiency level input.
 */
export type ProficiencyLevelRequest = {
  grade: string;
  description: string;
};

/**
 * Proficiency level output.
 */
export type ProficiencyLevelResponse = {
  grade: string;
  description: string;
};

/**
 * Request body for registration.
 */
export type RegisterRequest = {
  email: string;
  password: string;
  name: string;
  invite_token: string;
};

/**
 * Request to reorder objectives in a strand.
 */
export type ReorderObjectivesRequest = {
  objective_ids: Array<string>;
};

export type RetakePolicy = 'immediate' | 'delayed' | 'manual_approval' | 'none';

/**
 * Full review detail for educator.
 */
export type ReviewDetailResponse = {
  attempt: SocraticWebSocraticViewReviewAttemptResponse;
  evaluation: EvaluationResponse | null;
  transcript: Array<TranscriptSegmentResponse>;
  override_history: Array<OverrideResponse>;
  objective_id: string;
  objective_title: string;
  objective_description: string;
};

/**
 * List of reviews pending educator attention.
 */
export type ReviewListResponse = {
  reviews: Array<ReviewSummary>;
  total: number;
};

/**
 * Summary of a review for listing.
 */
export type ReviewSummary = {
  attempt_id: string;
  learner_id: string;
  learner_name?: string | null;
  objective_id: string;
  objective_title: string;
  grade: Grade | null;
  confidence_score: string | null;
  flags: Array<AssessmentFlag>;
  completed_at: string | null;
};

/**
 * Request to add a rubric criterion to an existing objective.
 */
export type RubricCriterionCreateRequest = {
  name: string;
  description: string;
  proficiency_levels?: Array<ProficiencyLevelRequest>;
};

/**
 * Rubric criterion input for creating/updating objectives.
 */
export type RubricCriterionRequest = {
  name: string;
  description: string;
  proficiency_levels?: Array<ProficiencyLevelRequest>;
};

/**
 * Rubric criterion output.
 */
export type RubricCriterionResponse = {
  criterion_id: string;
  objective_id: string;
  name: string;
  description: string;
  proficiency_levels?: Array<ProficiencyLevelResponse>;
};

/**
 * Request to update a rubric criterion.
 */
export type RubricCriterionUpdateRequest = {
  name?: string | null;
  description?: string | null;
  proficiency_levels?: Array<ProficiencyLevelRequest> | null;
};

/**
 * Request to send a learner message.
 */
export type SendMessageRequest = {
  content: string;
};

/**
 * Supported audio output formats.
 */
export type SpeechFormat = 'mp3' | 'opus' | 'aac' | 'flac' | 'wav' | 'pcm';

/**
 * Request to synthesize speech from text.
 */
export type SpeechRequest = {
  /**
   * Text to convert to speech
   */
  text: string;
  /**
   * Voice to use for synthesis
   */
  voice?: Voice;
  /**
   * Output audio format
   */
  format?: SpeechFormat;
  /**
   * Speech speed (0.25-4.0)
   */
  speed?: number;
};

/**
 * Immediate response when starting an assessment.
 *
 * The orientation message will be streamed via the /stream endpoint.
 */
export type StartAssessmentOkResponse = {
  attempt_id: string;
  assignment_id: string;
  objective_id: string;
  objective_title: string;
};

/**
 * Request to create a new strand.
 */
export type StrandCreateRequest = {
  name: string;
  description?: string | null;
};

/**
 * List of strands response.
 */
export type StrandListResponse = {
  strands: Array<StrandResponse>;
  total: number;
};

/**
 * Strand details response.
 */
export type StrandResponse = {
  strand_id: string;
  organization_id: string;
  created_by: string;
  name: string;
  description?: string | null;
  create_time: string;
  update_time?: string | null;
};

/**
 * Request to update a strand.
 */
export type StrandUpdateRequest = {
  name?: string | null;
  description?: string | null;
};

/**
 * Strand with ordered objectives.
 */
export type StrandWithObjectivesResponse = {
  strand_id: string;
  organization_id: string;
  created_by: string;
  name: string;
  description?: string | null;
  create_time: string;
  update_time?: string | null;
  objectives?: Array<ObjectiveInStrandResponse>;
};

/**
 * Response containing access token.
 */
export type TokenResponse = {
  access_token: string;
  token_type?: string;
  expires_at: string;
};

/**
 * A single message in the transcript.
 */
export type TranscriptMessageResponse = {
  segment_id: string;
  utterance_type: UtteranceType;
  content: string;
  start_time: string;
};

/**
 * Full assessment transcript.
 */
export type TranscriptResponse = {
  attempt_id: string;
  objective_title: string;
  started_at: string | null;
  completed_at: string | null;
  messages: Array<TranscriptMessageResponse>;
};

/**
 * A transcript segment in the review.
 */
export type TranscriptSegmentResponse = {
  segment_id: string;
  utterance_type: UtteranceType;
  content: string;
  start_time: string;
  prompt_index?: number | null;
};

/**
 * Response from transcription API.
 */
export type TranscriptionResponse = {
  text: string;
  duration?: number | null;
  language?: string | null;
};

/**
 * Response containing user information.
 */
export type UserResponse = {
  user_id: string;
  email: string;
  name: string;
  organization_id: string;
  role: string;
};

export type UtteranceType = 'learner' | 'interviewer' | 'system';

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

/**
 * Available TTS voices.
 */
export type Voice = 'alloy' | 'echo' | 'fable' | 'onyx' | 'nova' | 'shimmer';

/**
 * Assessment attempt response.
 */
export type SocraticWebSocraticViewAssignmentAttemptResponse = {
  attempt_id: string;
  assignment_id: string;
  learner_id: string;
  status: AttemptStatus;
  started_at?: string | null;
  completed_at?: string | null;
  grade?: Grade | null;
  confidence_score?: string | null;
  create_time: string;
};

/**
 * Assessment attempt in the review.
 */
export type SocraticWebSocraticViewReviewAttemptResponse = {
  attempt_id: string;
  learner_id: string;
  learner_name?: string | null;
  status: AttemptStatus;
  started_at: string | null;
  completed_at: string | null;
  grade: Grade | null;
  confidence_score: string | null;
};

export type LoginData = {
  body: LoginRequest;
  path?: never;
  query?: never;
  url: '/api/auth/login';
};

export type LoginErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
  /**
   * Successful Response
   */
  200: LoginOkResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type RegisterData = {
  body: RegisterRequest;
  path?: never;
  query?: never;
  url: '/api/auth/register';
};

export type RegisterErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
  /**
   * Successful Response
   */
  201: LoginOkResponse;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LogoutData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/auth/logout';
};

export type LogoutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
  /**
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type GetCurrentUserData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/auth/me';
};

export type GetCurrentUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCurrentUserError =
  GetCurrentUserErrors[keyof GetCurrentUserErrors];

export type GetCurrentUserResponses = {
  /**
   * Successful Response
   */
  200: UserResponse;
};

export type GetCurrentUserResponse =
  GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type CreateOrganizationData = {
  body: OrganizationCreateRequest;
  path?: never;
  query?: never;
  url: '/api/organizations';
};

export type CreateOrganizationErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateOrganizationError =
  CreateOrganizationErrors[keyof CreateOrganizationErrors];

export type CreateOrganizationResponses = {
  /**
   * Successful Response
   */
  201: OrganizationResponse;
};

export type CreateOrganizationResponse =
  CreateOrganizationResponses[keyof CreateOrganizationResponses];

export type GetOrganizationBySlugData = {
  body?: never;
  path: {
    slug: string;
  };
  query?: never;
  url: '/api/organizations/by-slug/{slug}';
};

export type GetOrganizationBySlugErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetOrganizationBySlugError =
  GetOrganizationBySlugErrors[keyof GetOrganizationBySlugErrors];

export type GetOrganizationBySlugResponses = {
  /**
   * Successful Response
   */
  200: OrganizationPublicResponse;
};

export type GetOrganizationBySlugResponse =
  GetOrganizationBySlugResponses[keyof GetOrganizationBySlugResponses];

export type GetOrganizationData = {
  body?: never;
  path: {
    organization_id: string;
  };
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/organizations/{organization_id}';
};

export type GetOrganizationErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetOrganizationError =
  GetOrganizationErrors[keyof GetOrganizationErrors];

export type GetOrganizationResponses = {
  /**
   * Successful Response
   */
  200: OrganizationResponse;
};

export type GetOrganizationResponse =
  GetOrganizationResponses[keyof GetOrganizationResponses];

export type InviteUserData = {
  body: InviteRequest;
  path: {
    organization_id: string;
  };
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/organizations/{organization_id}/invite';
};

export type InviteUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type InviteUserError = InviteUserErrors[keyof InviteUserErrors];

export type InviteUserResponses = {
  /**
   * Successful Response
   */
  200: InviteResponse;
};

export type InviteUserResponse = InviteUserResponses[keyof InviteUserResponses];

export type ListObjectivesData = {
  body?: never;
  path?: never;
  query?: {
    status_filter?: ObjectiveStatus | null;
    include_archived?: boolean;
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/objectives';
};

export type ListObjectivesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListObjectivesError =
  ListObjectivesErrors[keyof ListObjectivesErrors];

export type ListObjectivesResponses = {
  /**
   * Successful Response
   */
  200: ObjectiveListResponse;
};

export type ListObjectivesResponse =
  ListObjectivesResponses[keyof ListObjectivesResponses];

export type CreateObjectiveData = {
  body: ObjectiveCreateRequest;
  path?: never;
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/objectives';
};

export type CreateObjectiveErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateObjectiveError =
  CreateObjectiveErrors[keyof CreateObjectiveErrors];

export type CreateObjectiveResponses = {
  /**
   * Successful Response
   */
  201: ObjectiveResponse;
};

export type CreateObjectiveResponse =
  CreateObjectiveResponses[keyof CreateObjectiveResponses];

export type ArchiveObjectiveData = {
  body?: never;
  path: {
    objective_id: string;
  };
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/objectives/{objective_id}';
};

export type ArchiveObjectiveErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ArchiveObjectiveError =
  ArchiveObjectiveErrors[keyof ArchiveObjectiveErrors];

export type ArchiveObjectiveResponses = {
  /**
   * Successful Response
   */
  200: ObjectiveResponse;
};

export type ArchiveObjectiveResponse =
  ArchiveObjectiveResponses[keyof ArchiveObjectiveResponses];

export type GetObjectiveData = {
  body?: never;
  path: {
    objective_id: string;
  };
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/objectives/{objective_id}';
};

export type GetObjectiveErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetObjectiveError = GetObjectiveErrors[keyof GetObjectiveErrors];

export type GetObjectiveResponses = {
  /**
   * Successful Response
   */
  200: ObjectiveResponse;
};

export type GetObjectiveResponse =
  GetObjectiveResponses[keyof GetObjectiveResponses];

export type UpdateObjectiveData = {
  body: ObjectiveUpdateRequest;
  path: {
    objective_id: string;
  };
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/objectives/{objective_id}';
};

export type UpdateObjectiveErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateObjectiveError =
  UpdateObjectiveErrors[keyof UpdateObjectiveErrors];

export type UpdateObjectiveResponses = {
  /**
   * Successful Response
   */
  200: ObjectiveResponse;
};

export type UpdateObjectiveResponse =
  UpdateObjectiveResponses[keyof UpdateObjectiveResponses];

export type AddRubricCriterionData = {
  body: RubricCriterionCreateRequest;
  path: {
    objective_id: string;
  };
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/objectives/{objective_id}/criteria';
};

export type AddRubricCriterionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AddRubricCriterionError =
  AddRubricCriterionErrors[keyof AddRubricCriterionErrors];

export type AddRubricCriterionResponses = {
  /**
   * Successful Response
   */
  201: RubricCriterionResponse;
};

export type AddRubricCriterionResponse =
  AddRubricCriterionResponses[keyof AddRubricCriterionResponses];

export type DeleteRubricCriterionData = {
  body?: never;
  path: {
    objective_id: string;
    criterion_id: string;
  };
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/objectives/{objective_id}/criteria/{criterion_id}';
};

export type DeleteRubricCriterionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteRubricCriterionError =
  DeleteRubricCriterionErrors[keyof DeleteRubricCriterionErrors];

export type DeleteRubricCriterionResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteRubricCriterionResponse =
  DeleteRubricCriterionResponses[keyof DeleteRubricCriterionResponses];

export type UpdateRubricCriterionData = {
  body: RubricCriterionUpdateRequest;
  path: {
    objective_id: string;
    criterion_id: string;
  };
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/objectives/{objective_id}/criteria/{criterion_id}';
};

export type UpdateRubricCriterionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateRubricCriterionError =
  UpdateRubricCriterionErrors[keyof UpdateRubricCriterionErrors];

export type UpdateRubricCriterionResponses = {
  /**
   * Successful Response
   */
  200: RubricCriterionResponse;
};

export type UpdateRubricCriterionResponse =
  UpdateRubricCriterionResponses[keyof UpdateRubricCriterionResponses];

export type ListStrandsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/strands';
};

export type ListStrandsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListStrandsError = ListStrandsErrors[keyof ListStrandsErrors];

export type ListStrandsResponses = {
  /**
   * Successful Response
   */
  200: StrandListResponse;
};

export type ListStrandsResponse =
  ListStrandsResponses[keyof ListStrandsResponses];

export type CreateStrandData = {
  body: StrandCreateRequest;
  path?: never;
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/strands';
};

export type CreateStrandErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateStrandError = CreateStrandErrors[keyof CreateStrandErrors];

export type CreateStrandResponses = {
  /**
   * Successful Response
   */
  201: StrandResponse;
};

export type CreateStrandResponse =
  CreateStrandResponses[keyof CreateStrandResponses];

export type GetStrandData = {
  body?: never;
  path: {
    strand_id: string;
  };
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/strands/{strand_id}';
};

export type GetStrandErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetStrandError = GetStrandErrors[keyof GetStrandErrors];

export type GetStrandResponses = {
  /**
   * Successful Response
   */
  200: StrandWithObjectivesResponse;
};

export type GetStrandResponse = GetStrandResponses[keyof GetStrandResponses];

export type UpdateStrandData = {
  body: StrandUpdateRequest;
  path: {
    strand_id: string;
  };
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/strands/{strand_id}';
};

export type UpdateStrandErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateStrandError = UpdateStrandErrors[keyof UpdateStrandErrors];

export type UpdateStrandResponses = {
  /**
   * Successful Response
   */
  200: StrandResponse;
};

export type UpdateStrandResponse =
  UpdateStrandResponses[keyof UpdateStrandResponses];

export type AddObjectiveToStrandData = {
  body: ObjectiveInStrandRequest;
  path: {
    strand_id: string;
  };
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/strands/{strand_id}/objectives';
};

export type AddObjectiveToStrandErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AddObjectiveToStrandError =
  AddObjectiveToStrandErrors[keyof AddObjectiveToStrandErrors];

export type AddObjectiveToStrandResponses = {
  /**
   * Successful Response
   */
  201: ObjectiveInStrandResponse;
};

export type AddObjectiveToStrandResponse =
  AddObjectiveToStrandResponses[keyof AddObjectiveToStrandResponses];

export type ReorderObjectivesData = {
  body: ReorderObjectivesRequest;
  path: {
    strand_id: string;
  };
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/strands/{strand_id}/objectives';
};

export type ReorderObjectivesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReorderObjectivesError =
  ReorderObjectivesErrors[keyof ReorderObjectivesErrors];

export type ReorderObjectivesResponses = {
  /**
   * Successful Response
   */
  200: StrandWithObjectivesResponse;
};

export type ReorderObjectivesResponse =
  ReorderObjectivesResponses[keyof ReorderObjectivesResponses];

export type GetObjectiveDependenciesData = {
  body?: never;
  path: {
    strand_id: string;
    objective_id: string;
  };
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/strands/{strand_id}/objectives/{objective_id}/dependencies';
};

export type GetObjectiveDependenciesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetObjectiveDependenciesError =
  GetObjectiveDependenciesErrors[keyof GetObjectiveDependenciesErrors];

export type GetObjectiveDependenciesResponses = {
  /**
   * Successful Response
   */
  200: Array<ObjectiveDependencyResponse>;
};

export type GetObjectiveDependenciesResponse =
  GetObjectiveDependenciesResponses[keyof GetObjectiveDependenciesResponses];

export type AddObjectiveDependencyData = {
  body: ObjectiveDependencyRequest;
  path: {
    strand_id: string;
    objective_id: string;
  };
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/strands/{strand_id}/objectives/{objective_id}/dependencies';
};

export type AddObjectiveDependencyErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AddObjectiveDependencyError =
  AddObjectiveDependencyErrors[keyof AddObjectiveDependencyErrors];

export type AddObjectiveDependencyResponses = {
  /**
   * Successful Response
   */
  201: ObjectiveDependencyResponse;
};

export type AddObjectiveDependencyResponse =
  AddObjectiveDependencyResponses[keyof AddObjectiveDependencyResponses];

export type ListAssignmentsData = {
  body?: never;
  path?: never;
  query?: {
    objective_id?: string | null;
    assigned_to?: string | null;
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/assignments';
};

export type ListAssignmentsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListAssignmentsError =
  ListAssignmentsErrors[keyof ListAssignmentsErrors];

export type ListAssignmentsResponses = {
  /**
   * Successful Response
   */
  200: AssignmentListResponse;
};

export type ListAssignmentsResponse =
  ListAssignmentsResponses[keyof ListAssignmentsResponses];

export type CreateAssignmentData = {
  body: AssignmentCreateRequest;
  path?: never;
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/assignments';
};

export type CreateAssignmentErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateAssignmentError =
  CreateAssignmentErrors[keyof CreateAssignmentErrors];

export type CreateAssignmentResponses = {
  /**
   * Successful Response
   */
  201: AssignmentResponse;
};

export type CreateAssignmentResponse =
  CreateAssignmentResponses[keyof CreateAssignmentResponses];

export type CreateBulkAssignmentsData = {
  body: BulkAssignmentCreateRequest;
  path?: never;
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/assignments/bulk';
};

export type CreateBulkAssignmentsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateBulkAssignmentsError =
  CreateBulkAssignmentsErrors[keyof CreateBulkAssignmentsErrors];

export type CreateBulkAssignmentsResponses = {
  /**
   * Successful Response
   */
  201: AssignmentListResponse;
};

export type CreateBulkAssignmentsResponse =
  CreateBulkAssignmentsResponses[keyof CreateBulkAssignmentsResponses];

export type CancelAssignmentData = {
  body?: never;
  path: {
    assignment_id: string;
  };
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/assignments/{assignment_id}';
};

export type CancelAssignmentErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CancelAssignmentError =
  CancelAssignmentErrors[keyof CancelAssignmentErrors];

export type CancelAssignmentResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type CancelAssignmentResponse =
  CancelAssignmentResponses[keyof CancelAssignmentResponses];

export type GetAssignmentData = {
  body?: never;
  path: {
    assignment_id: string;
  };
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/assignments/{assignment_id}';
};

export type GetAssignmentErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetAssignmentError = GetAssignmentErrors[keyof GetAssignmentErrors];

export type GetAssignmentResponses = {
  /**
   * Successful Response
   */
  200: AssignmentWithAttemptsResponse;
};

export type GetAssignmentResponse =
  GetAssignmentResponses[keyof GetAssignmentResponses];

export type UpdateAssignmentData = {
  body: AssignmentUpdateRequest;
  path: {
    assignment_id: string;
  };
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/assignments/{assignment_id}';
};

export type UpdateAssignmentErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateAssignmentError =
  UpdateAssignmentErrors[keyof UpdateAssignmentErrors];

export type UpdateAssignmentResponses = {
  /**
   * Successful Response
   */
  200: AssignmentResponse;
};

export type UpdateAssignmentResponse =
  UpdateAssignmentResponses[keyof UpdateAssignmentResponses];

export type ListLearnersData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/learners';
};

export type ListLearnersErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListLearnersError = ListLearnersErrors[keyof ListLearnersErrors];

export type ListLearnersResponses = {
  /**
   * Successful Response
   */
  200: LearnerListResponse;
};

export type ListLearnersResponse =
  ListLearnersResponses[keyof ListLearnersResponses];

export type ListMyAssignmentsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/learners/me/assignments';
};

export type ListMyAssignmentsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListMyAssignmentsError =
  ListMyAssignmentsErrors[keyof ListMyAssignmentsErrors];

export type ListMyAssignmentsResponses = {
  /**
   * Successful Response
   */
  200: LearnerAssignmentsListResponse;
};

export type ListMyAssignmentsResponse =
  ListMyAssignmentsResponses[keyof ListMyAssignmentsResponses];

export type ListMyAttemptsData = {
  body?: never;
  path?: never;
  query?: {
    assignment_id?: string | null;
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/learners/me/attempts';
};

export type ListMyAttemptsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListMyAttemptsError =
  ListMyAttemptsErrors[keyof ListMyAttemptsErrors];

export type ListMyAttemptsResponses = {
  /**
   * Successful Response
   */
  200: LearnerAttemptsListResponse;
};

export type ListMyAttemptsResponse =
  ListMyAttemptsResponses[keyof ListMyAttemptsResponses];

export type GetLearnerDashboardData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/learners/me/dashboard';
};

export type GetLearnerDashboardErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetLearnerDashboardError =
  GetLearnerDashboardErrors[keyof GetLearnerDashboardErrors];

export type GetLearnerDashboardResponses = {
  /**
   * Successful Response
   */
  200: LearnerDashboardResponse;
};

export type GetLearnerDashboardResponse =
  GetLearnerDashboardResponses[keyof GetLearnerDashboardResponses];

export type GetMyAssignmentData = {
  body?: never;
  path: {
    assignment_id: string;
  };
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/learners/me/assignments/{assignment_id}';
};

export type GetMyAssignmentErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetMyAssignmentError =
  GetMyAssignmentErrors[keyof GetMyAssignmentErrors];

export type GetMyAssignmentResponses = {
  /**
   * Successful Response
   */
  200: AssignmentWithAttemptsResponse;
};

export type GetMyAssignmentResponse =
  GetMyAssignmentResponses[keyof GetMyAssignmentResponses];

export type GetLearnerAssignmentsData = {
  body?: never;
  path: {
    learner_id: string;
  };
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/learners/{learner_id}/assignments';
};

export type GetLearnerAssignmentsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetLearnerAssignmentsError =
  GetLearnerAssignmentsErrors[keyof GetLearnerAssignmentsErrors];

export type GetLearnerAssignmentsResponses = {
  /**
   * Successful Response
   */
  200: Array<AssignmentWithAttemptsResponse>;
};

export type GetLearnerAssignmentsResponse =
  GetLearnerAssignmentsResponses[keyof GetLearnerAssignmentsResponses];

export type StartAssessmentData = {
  body?: never;
  path: {
    assignment_id: string;
  };
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/assessments/{assignment_id}/start';
};

export type StartAssessmentErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type StartAssessmentError =
  StartAssessmentErrors[keyof StartAssessmentErrors];

export type StartAssessmentResponses = {
  /**
   * Successful Response
   */
  200: StartAssessmentOkResponse;
};

export type StartAssessmentResponse =
  StartAssessmentResponses[keyof StartAssessmentResponses];

export type StreamAssessmentData = {
  body?: never;
  path: {
    attempt_id: string;
  };
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/assessments/{attempt_id}/stream';
};

export type StreamAssessmentErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type StreamAssessmentError =
  StreamAssessmentErrors[keyof StreamAssessmentErrors];

export type StreamAssessmentResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type SendAssessmentMessageData = {
  body: SendMessageRequest;
  path: {
    attempt_id: string;
  };
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/assessments/{attempt_id}/message';
};

export type SendAssessmentMessageErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SendAssessmentMessageError =
  SendAssessmentMessageErrors[keyof SendAssessmentMessageErrors];

export type SendAssessmentMessageResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetAssessmentStatusData = {
  body?: never;
  path: {
    attempt_id: string;
  };
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/assessments/{attempt_id}/status';
};

export type GetAssessmentStatusErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetAssessmentStatusError =
  GetAssessmentStatusErrors[keyof GetAssessmentStatusErrors];

export type GetAssessmentStatusResponses = {
  /**
   * Successful Response
   */
  200: AssessmentStatusResponse;
};

export type GetAssessmentStatusResponse =
  GetAssessmentStatusResponses[keyof GetAssessmentStatusResponses];

export type CompleteAssessmentData = {
  body: CompleteAssessmentRequest;
  path: {
    attempt_id: string;
  };
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/assessments/{attempt_id}/complete';
};

export type CompleteAssessmentErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CompleteAssessmentError =
  CompleteAssessmentErrors[keyof CompleteAssessmentErrors];

export type CompleteAssessmentResponses = {
  /**
   * Successful Response
   */
  200: CompleteAssessmentOkResponse;
};

export type CompleteAssessmentResponse =
  CompleteAssessmentResponses[keyof CompleteAssessmentResponses];

export type GetAssessmentTranscriptData = {
  body?: never;
  path: {
    attempt_id: string;
  };
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/assessments/{attempt_id}/transcript';
};

export type GetAssessmentTranscriptErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetAssessmentTranscriptError =
  GetAssessmentTranscriptErrors[keyof GetAssessmentTranscriptErrors];

export type GetAssessmentTranscriptResponses = {
  /**
   * Successful Response
   */
  200: TranscriptResponse;
};

export type GetAssessmentTranscriptResponse =
  GetAssessmentTranscriptResponses[keyof GetAssessmentTranscriptResponses];

export type TriggerEvaluationData = {
  body?: never;
  path: {
    attempt_id: string;
  };
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/assessments/{attempt_id}/evaluate';
};

export type TriggerEvaluationErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type TriggerEvaluationError =
  TriggerEvaluationErrors[keyof TriggerEvaluationErrors];

export type TriggerEvaluationResponses = {
  /**
   * Successful Response
   */
  200: {
    [key: string]: unknown;
  };
};

export type TriggerEvaluationResponse =
  TriggerEvaluationResponses[keyof TriggerEvaluationResponses];

export type ListPendingReviewsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/reviews';
};

export type ListPendingReviewsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListPendingReviewsError =
  ListPendingReviewsErrors[keyof ListPendingReviewsErrors];

export type ListPendingReviewsResponses = {
  /**
   * Successful Response
   */
  200: ReviewListResponse;
};

export type ListPendingReviewsResponse =
  ListPendingReviewsResponses[keyof ListPendingReviewsResponses];

export type GetReviewDetailData = {
  body?: never;
  path: {
    attempt_id: string;
  };
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/reviews/{attempt_id}';
};

export type GetReviewDetailErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetReviewDetailError =
  GetReviewDetailErrors[keyof GetReviewDetailErrors];

export type GetReviewDetailResponses = {
  /**
   * Successful Response
   */
  200: ReviewDetailResponse;
};

export type GetReviewDetailResponse =
  GetReviewDetailResponses[keyof GetReviewDetailResponses];

export type AcceptGradeData = {
  body: GradeAcceptRequest;
  path: {
    attempt_id: string;
  };
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/reviews/{attempt_id}/accept';
};

export type AcceptGradeErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AcceptGradeError = AcceptGradeErrors[keyof AcceptGradeErrors];

export type AcceptGradeResponses = {
  /**
   * Successful Response
   */
  200: ReviewDetailResponse;
};

export type AcceptGradeResponse =
  AcceptGradeResponses[keyof AcceptGradeResponses];

export type OverrideGradeData = {
  body: GradeOverrideRequest;
  path: {
    attempt_id: string;
  };
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/reviews/{attempt_id}/override';
};

export type OverrideGradeErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type OverrideGradeError = OverrideGradeErrors[keyof OverrideGradeErrors];

export type OverrideGradeResponses = {
  /**
   * Successful Response
   */
  200: ReviewDetailResponse;
};

export type OverrideGradeResponse =
  OverrideGradeResponses[keyof OverrideGradeResponses];

export type AddFeedbackData = {
  body: FeedbackRequest;
  path: {
    attempt_id: string;
  };
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/reviews/{attempt_id}/feedback';
};

export type AddFeedbackErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AddFeedbackError = AddFeedbackErrors[keyof AddFeedbackErrors];

export type AddFeedbackResponses = {
  /**
   * Successful Response
   */
  200: ReviewDetailResponse;
};

export type AddFeedbackResponse =
  AddFeedbackResponses[keyof AddFeedbackResponses];

export type SynthesizeSpeechData = {
  body: SpeechRequest;
  path?: never;
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/speech';
};

export type SynthesizeSpeechErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SynthesizeSpeechError =
  SynthesizeSpeechErrors[keyof SynthesizeSpeechErrors];

export type SynthesizeSpeechResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type TranscribeAudioData = {
  body: BodyTranscribeAudio;
  path?: never;
  query?: {
    /**
     * JWT token (for EventSource which can't set headers)
     */
    token?: string | null;
  };
  url: '/api/transcription';
};

export type TranscribeAudioErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type TranscribeAudioError =
  TranscribeAudioErrors[keyof TranscribeAudioErrors];

export type TranscribeAudioResponses = {
  /**
   * Successful Response
   */
  200: TranscriptionResponse;
};

export type TranscribeAudioResponse =
  TranscribeAudioResponses[keyof TranscribeAudioResponses];

export type ClientOptions = {
  baseUrl: 'http://localhost:8089' | (string & {});
};
