// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options as ClientOptions,
  type TDataShape,
  type Client,
  formDataBodySerializer,
} from '@hey-api/client-fetch';
import type {
  LoginData,
  LoginResponse,
  LoginError,
  RegisterData,
  RegisterResponse,
  RegisterError,
  LogoutData,
  LogoutResponse,
  LogoutError,
  GetCurrentUserData,
  GetCurrentUserResponse,
  GetCurrentUserError,
  CreateOrganizationData,
  CreateOrganizationResponse,
  CreateOrganizationError,
  GetOrganizationBySlugData,
  GetOrganizationBySlugResponse,
  GetOrganizationBySlugError,
  GetOrganizationData,
  GetOrganizationResponse,
  GetOrganizationError,
  InviteUserData,
  InviteUserResponse,
  InviteUserError,
  ListObjectivesData,
  ListObjectivesResponse,
  ListObjectivesError,
  CreateObjectiveData,
  CreateObjectiveResponse,
  CreateObjectiveError,
  ArchiveObjectiveData,
  ArchiveObjectiveResponse,
  ArchiveObjectiveError,
  GetObjectiveData,
  GetObjectiveResponse,
  GetObjectiveError,
  UpdateObjectiveData,
  UpdateObjectiveResponse,
  UpdateObjectiveError,
  AddRubricCriterionData,
  AddRubricCriterionResponse,
  AddRubricCriterionError,
  DeleteRubricCriterionData,
  DeleteRubricCriterionResponse,
  DeleteRubricCriterionError,
  UpdateRubricCriterionData,
  UpdateRubricCriterionResponse,
  UpdateRubricCriterionError,
  ListStrandsData,
  ListStrandsResponse,
  ListStrandsError,
  CreateStrandData,
  CreateStrandResponse,
  CreateStrandError,
  GetStrandData,
  GetStrandResponse,
  GetStrandError,
  UpdateStrandData,
  UpdateStrandResponse,
  UpdateStrandError,
  AddObjectiveToStrandData,
  AddObjectiveToStrandResponse,
  AddObjectiveToStrandError,
  ReorderObjectivesData,
  ReorderObjectivesResponse,
  ReorderObjectivesError,
  GetObjectiveDependenciesData,
  GetObjectiveDependenciesResponse,
  GetObjectiveDependenciesError,
  AddObjectiveDependencyData,
  AddObjectiveDependencyResponse,
  AddObjectiveDependencyError,
  ListAssignmentsData,
  ListAssignmentsResponse,
  ListAssignmentsError,
  CreateAssignmentData,
  CreateAssignmentResponse,
  CreateAssignmentError,
  CreateBulkAssignmentsData,
  CreateBulkAssignmentsResponse,
  CreateBulkAssignmentsError,
  CancelAssignmentData,
  CancelAssignmentResponse,
  CancelAssignmentError,
  GetAssignmentData,
  GetAssignmentResponse,
  GetAssignmentError,
  UpdateAssignmentData,
  UpdateAssignmentResponse,
  UpdateAssignmentError,
  ListLearnersData,
  ListLearnersResponse,
  ListLearnersError,
  ListMyAssignmentsData,
  ListMyAssignmentsResponse,
  ListMyAssignmentsError,
  ListMyAttemptsData,
  ListMyAttemptsResponse,
  ListMyAttemptsError,
  GetLearnerDashboardData,
  GetLearnerDashboardResponse,
  GetLearnerDashboardError,
  GetMyAssignmentData,
  GetMyAssignmentResponse,
  GetMyAssignmentError,
  GetLearnerAssignmentsData,
  GetLearnerAssignmentsResponse,
  GetLearnerAssignmentsError,
  StartAssessmentData,
  StartAssessmentResponse,
  StartAssessmentError,
  StreamAssessmentData,
  StreamAssessmentError,
  SendAssessmentMessageData,
  SendAssessmentMessageError,
  GetAssessmentStatusData,
  GetAssessmentStatusResponse,
  GetAssessmentStatusError,
  CompleteAssessmentData,
  CompleteAssessmentResponse,
  CompleteAssessmentError,
  GetAssessmentTranscriptData,
  GetAssessmentTranscriptResponse,
  GetAssessmentTranscriptError,
  TriggerEvaluationData,
  TriggerEvaluationResponse,
  TriggerEvaluationError,
  UploadAssessmentVideoData,
  UploadAssessmentVideoResponse,
  UploadAssessmentVideoError,
  ListPendingReviewsData,
  ListPendingReviewsResponse,
  ListPendingReviewsError,
  GetReviewDetailData,
  GetReviewDetailResponse,
  GetReviewDetailError,
  AcceptGradeData,
  AcceptGradeResponse,
  AcceptGradeError,
  OverrideGradeData,
  OverrideGradeResponse,
  OverrideGradeError,
  AddFeedbackData,
  AddFeedbackResponse,
  AddFeedbackError,
  GetSynchronizedTranscriptData,
  GetSynchronizedTranscriptResponse,
  GetSynchronizedTranscriptError,
  SynthesizeSpeechData,
  SynthesizeSpeechError,
  TranscribeAudioData,
  TranscribeAudioResponse,
  TranscribeAudioError,
} from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Login
 * Authenticate a user and return access token.
 */
export const login = <ThrowOnError extends boolean = false>(
  options: Options<LoginData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    LoginResponse,
    LoginError,
    ThrowOnError
  >({
    url: '/api/auth/login',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Register
 * Register a new user with an invite token.
 */
export const register = <ThrowOnError extends boolean = false>(
  options: Options<RegisterData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    RegisterResponse,
    RegisterError,
    ThrowOnError
  >({
    url: '/api/auth/register',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Logout
 * Logout the current user.
 *
 * Note: With JWT tokens, logout is primarily handled client-side
 * by discarding the token. This endpoint is provided for API consistency.
 */
export const logout = <ThrowOnError extends boolean = false>(
  options?: Options<LogoutData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).post<
    LogoutResponse,
    LogoutError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/auth/logout',
    ...options,
  });
};

/**
 * Get Me
 * Get the current authenticated user.
 */
export const getCurrentUser = <ThrowOnError extends boolean = false>(
  options?: Options<GetCurrentUserData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetCurrentUserResponse,
    GetCurrentUserError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/auth/me',
    ...options,
  });
};

/**
 * Create Organization
 * Create a new organization with an initial admin user.
 *
 * This is the initial setup endpoint for creating an organization.
 * The admin user will be created with the educator role.
 */
export const createOrganization = <ThrowOnError extends boolean = false>(
  options: Options<CreateOrganizationData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateOrganizationResponse,
    CreateOrganizationError,
    ThrowOnError
  >({
    url: '/api/organizations',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Get Organization By Slug
 * Get public organization information by slug.
 *
 * This endpoint does not require authentication and returns minimal
 * organization info for use on login pages.
 */
export const getOrganizationBySlug = <ThrowOnError extends boolean = false>(
  options: Options<GetOrganizationBySlugData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetOrganizationBySlugResponse,
    GetOrganizationBySlugError,
    ThrowOnError
  >({
    url: '/api/organizations/by-slug/{slug}',
    ...options,
  });
};

/**
 * Get Organization
 * Get organization details.
 *
 * Users can only view their own organization.
 */
export const getOrganization = <ThrowOnError extends boolean = false>(
  options: Options<GetOrganizationData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetOrganizationResponse,
    GetOrganizationError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/organizations/{organization_id}',
    ...options,
  });
};

/**
 * Invite User
 * Generate an invite token for a new user.
 *
 * Only educators can invite users to their organization.
 */
export const inviteUser = <ThrowOnError extends boolean = false>(
  options: Options<InviteUserData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    InviteUserResponse,
    InviteUserError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/organizations/{organization_id}/invite',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * List Objectives
 * List objectives for the educator's organization.
 *
 * Only educators can list objectives.
 * Archived objectives are excluded by default unless include_archived=True.
 */
export const listObjectives = <ThrowOnError extends boolean = false>(
  options?: Options<ListObjectivesData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListObjectivesResponse,
    ListObjectivesError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/objectives',
    ...options,
  });
};

/**
 * Create Objective
 * Create a new objective with optional rubric criteria.
 *
 * Only educators can create objectives.
 */
export const createObjective = <ThrowOnError extends boolean = false>(
  options: Options<CreateObjectiveData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateObjectiveResponse,
    CreateObjectiveError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/objectives',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Archive Objective
 * Archive an objective (soft delete).
 *
 * Only educators can archive objectives.
 */
export const archiveObjective = <ThrowOnError extends boolean = false>(
  options: Options<ArchiveObjectiveData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    ArchiveObjectiveResponse,
    ArchiveObjectiveError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/objectives/{objective_id}',
    ...options,
  });
};

/**
 * Get Objective
 * Get objective details.
 *
 * Only educators can view objective details.
 */
export const getObjective = <ThrowOnError extends boolean = false>(
  options: Options<GetObjectiveData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetObjectiveResponse,
    GetObjectiveError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/objectives/{objective_id}',
    ...options,
  });
};

/**
 * Update Objective
 * Update an objective.
 *
 * Only educators can update objectives.
 */
export const updateObjective = <ThrowOnError extends boolean = false>(
  options: Options<UpdateObjectiveData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).put<
    UpdateObjectiveResponse,
    UpdateObjectiveError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/objectives/{objective_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Add Rubric Criterion
 * Add a rubric criterion to an objective.
 *
 * Only educators can add rubric criteria.
 */
export const addRubricCriterion = <ThrowOnError extends boolean = false>(
  options: Options<AddRubricCriterionData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    AddRubricCriterionResponse,
    AddRubricCriterionError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/objectives/{objective_id}/criteria',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Delete Rubric Criterion
 * Delete a rubric criterion.
 *
 * Only educators can delete rubric criteria.
 */
export const deleteRubricCriterion = <ThrowOnError extends boolean = false>(
  options: Options<DeleteRubricCriterionData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteRubricCriterionResponse,
    DeleteRubricCriterionError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/objectives/{objective_id}/criteria/{criterion_id}',
    ...options,
  });
};

/**
 * Update Rubric Criterion
 * Update a rubric criterion.
 *
 * Only educators can update rubric criteria.
 */
export const updateRubricCriterion = <ThrowOnError extends boolean = false>(
  options: Options<UpdateRubricCriterionData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).put<
    UpdateRubricCriterionResponse,
    UpdateRubricCriterionError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/objectives/{objective_id}/criteria/{criterion_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * List Strands
 * List strands for the educator's organization.
 *
 * Only educators can list strands.
 */
export const listStrands = <ThrowOnError extends boolean = false>(
  options?: Options<ListStrandsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListStrandsResponse,
    ListStrandsError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/strands',
    ...options,
  });
};

/**
 * Create Strand
 * Create a new strand.
 *
 * Only educators can create strands.
 */
export const createStrand = <ThrowOnError extends boolean = false>(
  options: Options<CreateStrandData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateStrandResponse,
    CreateStrandError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/strands',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Get Strand
 * Get strand details with ordered objectives.
 *
 * Only educators can view strand details.
 */
export const getStrand = <ThrowOnError extends boolean = false>(
  options: Options<GetStrandData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetStrandResponse,
    GetStrandError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/strands/{strand_id}',
    ...options,
  });
};

/**
 * Update Strand
 * Update a strand.
 *
 * Only educators can update strands.
 */
export const updateStrand = <ThrowOnError extends boolean = false>(
  options: Options<UpdateStrandData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).put<
    UpdateStrandResponse,
    UpdateStrandError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/strands/{strand_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Add Objective To Strand
 * Add an objective to a strand at a specific position.
 *
 * Only educators can add objectives to strands.
 */
export const addObjectiveToStrand = <ThrowOnError extends boolean = false>(
  options: Options<AddObjectiveToStrandData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    AddObjectiveToStrandResponse,
    AddObjectiveToStrandError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/strands/{strand_id}/objectives',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Reorder Objectives
 * Reorder objectives in a strand.
 *
 * The objective_ids list should contain all objective IDs in the desired order.
 * Only educators can reorder objectives.
 */
export const reorderObjectives = <ThrowOnError extends boolean = false>(
  options: Options<ReorderObjectivesData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).put<
    ReorderObjectivesResponse,
    ReorderObjectivesError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/strands/{strand_id}/objectives',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Get Objective Dependencies
 * Get dependencies for an objective.
 *
 * Only educators can view dependencies.
 */
export const getObjectiveDependencies = <ThrowOnError extends boolean = false>(
  options: Options<GetObjectiveDependenciesData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetObjectiveDependenciesResponse,
    GetObjectiveDependenciesError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/strands/{strand_id}/objectives/{objective_id}/dependencies',
    ...options,
  });
};

/**
 * Add Objective Dependency
 * Add a dependency between objectives in a strand.
 *
 * The objective depends on the specified prerequisite objective.
 * Only educators can add dependencies.
 */
export const addObjectiveDependency = <ThrowOnError extends boolean = false>(
  options: Options<AddObjectiveDependencyData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    AddObjectiveDependencyResponse,
    AddObjectiveDependencyError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/strands/{strand_id}/objectives/{objective_id}/dependencies',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * List Assignments
 * List assignments.
 *
 * Educators can filter by objective or learner.
 */
export const listAssignments = <ThrowOnError extends boolean = false>(
  options?: Options<ListAssignmentsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListAssignmentsResponse,
    ListAssignmentsError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/assignments',
    ...options,
  });
};

/**
 * Create Assignment
 * Create a new assignment for a learner.
 *
 * Only educators can create assignments.
 */
export const createAssignment = <ThrowOnError extends boolean = false>(
  options: Options<CreateAssignmentData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateAssignmentResponse,
    CreateAssignmentError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/assignments',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Create Bulk Assignments
 * Create assignments for multiple learners at once.
 *
 * Only educators can create assignments.
 */
export const createBulkAssignments = <ThrowOnError extends boolean = false>(
  options: Options<CreateBulkAssignmentsData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateBulkAssignmentsResponse,
    CreateBulkAssignmentsError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/assignments/bulk',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Cancel Assignment
 * Cancel (delete) an assignment.
 *
 * Only educators can cancel assignments. This is a hard delete.
 */
export const cancelAssignment = <ThrowOnError extends boolean = false>(
  options: Options<CancelAssignmentData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    CancelAssignmentResponse,
    CancelAssignmentError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/assignments/{assignment_id}',
    ...options,
  });
};

/**
 * Get Assignment
 * Get assignment details with attempts.
 *
 * Educators can view any assignment in their organization.
 */
export const getAssignment = <ThrowOnError extends boolean = false>(
  options: Options<GetAssignmentData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetAssignmentResponse,
    GetAssignmentError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/assignments/{assignment_id}',
    ...options,
  });
};

/**
 * Update Assignment
 * Update an assignment.
 *
 * Only educators can update assignments.
 */
export const updateAssignment = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAssignmentData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).put<
    UpdateAssignmentResponse,
    UpdateAssignmentError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/assignments/{assignment_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * List Learners
 * List all learners in the organization.
 *
 * Only educators can list learners.
 */
export const listLearners = <ThrowOnError extends boolean = false>(
  options?: Options<ListLearnersData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListLearnersResponse,
    ListLearnersError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/learners',
    ...options,
  });
};

/**
 * List My Assignments
 * Get all assignments for the current learner.
 *
 * Returns assignments with objective info, attempt counts, and availability status.
 */
export const listMyAssignments = <ThrowOnError extends boolean = false>(
  options?: Options<ListMyAssignmentsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListMyAssignmentsResponse,
    ListMyAssignmentsError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/learners/me/assignments',
    ...options,
  });
};

/**
 * List My Attempts
 * Get all attempts for the current learner.
 *
 * Returns attempts with objective info, review status, and feedback (if reviewed).
 *
 * Args:
 * assignment_id: Optional filter to show attempts for a specific assignment.
 */
export const listMyAttempts = <ThrowOnError extends boolean = false>(
  options?: Options<ListMyAttemptsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListMyAttemptsResponse,
    ListMyAttemptsError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/learners/me/attempts',
    ...options,
  });
};

/**
 * Get Learner Dashboard
 * Get the current learner's dashboard with all assignments.
 *
 * Shows assignment status, grades, and availability.
 */
export const getLearnerDashboard = <ThrowOnError extends boolean = false>(
  options?: Options<GetLearnerDashboardData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetLearnerDashboardResponse,
    GetLearnerDashboardError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/learners/me/dashboard',
    ...options,
  });
};

/**
 * Get My Assignment
 * Get details of a specific assignment for the current learner.
 */
export const getMyAssignment = <ThrowOnError extends boolean = false>(
  options: Options<GetMyAssignmentData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetMyAssignmentResponse,
    GetMyAssignmentError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/learners/me/assignments/{assignment_id}',
    ...options,
  });
};

/**
 * Get Learner Assignments
 * Get all assignments for a specific learner.
 *
 * Only educators can view learner assignments.
 */
export const getLearnerAssignments = <ThrowOnError extends boolean = false>(
  options: Options<GetLearnerAssignmentsData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetLearnerAssignmentsResponse,
    GetLearnerAssignmentsError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/learners/{learner_id}/assignments',
    ...options,
  });
};

/**
 * Start Assessment Route
 * Start a new assessment attempt.
 *
 * Returns immediately with attempt metadata. The orientation message
 * will be streamed via the GET /stream endpoint.
 */
export const startAssessment = <ThrowOnError extends boolean = false>(
  options: Options<StartAssessmentData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    StartAssessmentResponse,
    StartAssessmentError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/assessments/{assignment_id}/start',
    ...options,
  });
};

/**
 * Stream Assessment Route
 * Stream assessment events via Server-Sent Events.
 *
 * Supports reconnection via Last-Event-ID header.
 *
 * Event types:
 * - token: Partial content token {"content": "..."}
 * - message_done: AI message complete
 * - assessment_complete: Assessment finished {"evaluation_id": "..."}
 * - error: Error occurred {"message": "...", "recoverable": bool}
 */
export const streamAssessment = <ThrowOnError extends boolean = false>(
  options: Options<StreamAssessmentData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    unknown,
    StreamAssessmentError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/assessments/{attempt_id}/stream',
    ...options,
  });
};

/**
 * Send Message Route
 * Send a learner message.
 *
 * Returns 202 Accepted immediately. The AI response will be
 * streamed via the GET /stream endpoint.
 */
export const sendAssessmentMessage = <ThrowOnError extends boolean = false>(
  options: Options<SendAssessmentMessageData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    unknown,
    SendAssessmentMessageError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/assessments/{attempt_id}/message',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Get Status Route
 * Get the current status of an assessment attempt.
 */
export const getAssessmentStatus = <ThrowOnError extends boolean = false>(
  options: Options<GetAssessmentStatusData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetAssessmentStatusResponse,
    GetAssessmentStatusError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/assessments/{attempt_id}/status',
    ...options,
  });
};

/**
 * Complete Assessment Route
 * Complete an assessment attempt.
 */
export const completeAssessment = <ThrowOnError extends boolean = false>(
  options: Options<CompleteAssessmentData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CompleteAssessmentResponse,
    CompleteAssessmentError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/assessments/{attempt_id}/complete',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Get Transcript Route
 * Get the full transcript of an assessment attempt.
 */
export const getAssessmentTranscript = <ThrowOnError extends boolean = false>(
  options: Options<GetAssessmentTranscriptData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetAssessmentTranscriptResponse,
    GetAssessmentTranscriptError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/assessments/{attempt_id}/transcript',
    ...options,
  });
};

/**
 * Trigger Evaluation Route
 * Trigger AI evaluation for a completed assessment.
 *
 * This endpoint is called by educators or automated systems after
 * an assessment is completed. It runs the evaluation pipeline and
 * updates the attempt status to Evaluated.
 */
export const triggerEvaluation = <ThrowOnError extends boolean = false>(
  options: Options<TriggerEvaluationData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    TriggerEvaluationResponse,
    TriggerEvaluationError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/assessments/{attempt_id}/evaluate',
    ...options,
  });
};

/**
 * Upload Video Route
 * Upload the recorded video for an assessment attempt.
 *
 * The video is uploaded to object storage and the attempt is updated
 * with the video URL.
 */
export const uploadAssessmentVideo = <ThrowOnError extends boolean = false>(
  options: Options<UploadAssessmentVideoData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    UploadAssessmentVideoResponse,
    UploadAssessmentVideoError,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/assessments/{attempt_id}/video',
    ...options,
    headers: {
      'Content-Type': null,
      ...options?.headers,
    },
  });
};

/**
 * List Pending Reviews
 * List all attempts pending educator review.
 */
export const listPendingReviews = <ThrowOnError extends boolean = false>(
  options?: Options<ListPendingReviewsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListPendingReviewsResponse,
    ListPendingReviewsError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/reviews',
    ...options,
  });
};

/**
 * Get Review Detail
 * Get full review detail for an attempt.
 */
export const getReviewDetail = <ThrowOnError extends boolean = false>(
  options: Options<GetReviewDetailData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetReviewDetailResponse,
    GetReviewDetailError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/reviews/{attempt_id}',
    ...options,
  });
};

/**
 * Accept Grade
 * Accept the AI-assigned grade and mark as reviewed.
 */
export const acceptGrade = <ThrowOnError extends boolean = false>(
  options: Options<AcceptGradeData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    AcceptGradeResponse,
    AcceptGradeError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/reviews/{attempt_id}/accept',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Override Grade
 * Override the AI-assigned grade with educator's judgment.
 */
export const overrideGrade = <ThrowOnError extends boolean = false>(
  options: Options<OverrideGradeData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    OverrideGradeResponse,
    OverrideGradeError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/reviews/{attempt_id}/override',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Add Feedback
 * Add qualitative feedback to a reviewed attempt.
 */
export const addFeedback = <ThrowOnError extends boolean = false>(
  options: Options<AddFeedbackData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    AddFeedbackResponse,
    AddFeedbackError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/reviews/{attempt_id}/feedback',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Get Synchronized Transcript
 * Get transcript with word-level timing data for video synchronization.
 *
 * Returns transcript segments with word timings for video playback sync.
 * This enables "click word to seek" and "highlight current word" features.
 */
export const getSynchronizedTranscript = <ThrowOnError extends boolean = false>(
  options: Options<GetSynchronizedTranscriptData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetSynchronizedTranscriptResponse,
    GetSynchronizedTranscriptError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/reviews/{attempt_id}/transcript/synchronized',
    ...options,
  });
};

/**
 * Synthesize Speech Route
 * Synthesize speech from text.
 *
 * Returns audio data in the requested format.
 */
export const synthesizeSpeech = <ThrowOnError extends boolean = false>(
  options: Options<SynthesizeSpeechData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    unknown,
    SynthesizeSpeechError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/speech',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Transcribe Audio Route
 * Transcribe audio to text using OpenAI Whisper.
 *
 * Accepts audio files up to 25MB in common formats (webm, mp3, mp4, wav, etc.).
 * Returns the transcribed text along with optional duration and detected language.
 *
 * If include_word_timings is true, also returns word-level timing data for
 * synchronized playback features.
 *
 * The learner must be authenticated to use this endpoint.
 */
export const transcribeAudio = <ThrowOnError extends boolean = false>(
  options: Options<TranscribeAudioData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    TranscribeAudioResponse,
    TranscribeAudioError,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/transcription',
    ...options,
    headers: {
      'Content-Type': null,
      ...options?.headers,
    },
  });
};
